In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
from IPython.display import display, Markdown

In [2]:
movies = "movies.csv"
ratings = "ratings.csv"
links = "links.csv"
tags = "tags.csv"

path = os.path.join("../../..", "data/laboration_1/ml-latest/")

In [3]:
df_movies = pd.read_csv(path + movies)
df_ratings = pd.read_csv(path + ratings)
df_links = pd.read_csv(path + links)
df_tags = pd.read_csv(path + tags)

In [4]:
display(
    Markdown("### Filmer"),
    len(df_movies),
    Markdown("### Ratings"),
    len(df_ratings),
    Markdown("### Links"),
    len(df_links),
    Markdown("### Tags"),
    len(df_tags)
)

### Filmer

86537

### Ratings

33832162

### Links

86537

### Tags

2328315

In [5]:
display(
    Markdown("### Filmer"),
    df_movies.head(),
    Markdown("### Ratings"),
    df_ratings.head(),
    Markdown("### Links"),
    df_links.head(),
    Markdown("### Tags"),
    df_tags.head()
)

### Filmer

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

### Ratings

   userId  movieId  rating   timestamp
0       1        1     4.0  1225734739
1       1      110     4.0  1225865086
2       1      158     4.0  1225733503
3       1      260     4.5  1225735204
4       1      356     5.0  1225735119

### Links

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

### Tags

   userId  movieId            tag   timestamp
0      10      260   good vs evil  1430666558
1      10      260  Harrison Ford  1430666505
2      10      260         sci-fi  1430666538
3      14     1221      Al Pacino  1311600756
4      14     1221          mafia  1311600746

In [6]:
display(
    Markdown("### Filmer"),
    df_movies.tail(),
    Markdown("### Ratings"),
    df_ratings.tail(),
    Markdown("### Links"),
    df_links.tail(),
    Markdown("### Tags"),
    df_tags.tail()
)

### Filmer

,movieId,title,genres
86532,288967,State of Siege: Temple Attack (2021),Action|Drama
86533,288971,Ouija Japan (2021),Action|Horror
86534,288975,The Men Who Made the Movies: Howard Hawks (1973),Documentary
86535,288977,Skinford: Death Sentence (2023),Crime|Thriller
86536,288983,UNZIPPED: An Autopsy of American Inequality (2...,Documentary

### Ratings

          userId  movieId  rating   timestamp
33832157  330975     8340     2.0  1091583256
33832158  330975     8493     2.5  1091585709
33832159  330975     8622     4.0  1091581777
33832160  330975     8665     3.0  1091581765
33832161  330975     8783     2.5  1091581799

### Links

       movieId    imdbId     tmdbId
86532   288967  14418234   845861.0
86533   288971  11162178   878958.0
86534   288975     70199   150392.0
86535   288977  23050520  1102551.0
86536   288983  11644948   940588.0

### Tags

         userId  movieId                  tag   timestamp
2328310  330923   176599  politically correct  1507547491
2328311  330933     3317        coming of age  1351279384
2328312  330933     3317            sexuality  1351279389
2328313  330947     5782       Not Luc Besson  1154110902
2328314  330947    44191           comic book  1154271525

In [7]:
display(
    Markdown("### Filmer"),
    df_movies.head(),
    df_movies.tail(),
    Markdown("### Ratings"),
    df_ratings.head(),
    df_ratings.tail(),
    Markdown("### Links"),
    df_links.head(),
    df_links.tail(),
    Markdown("### Tags"),
    df_tags.head(),
    df_tags.tail()
)

### Filmer

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

,movieId,title,genres
86532,288967,State of Siege: Temple Attack (2021),Action|Drama
86533,288971,Ouija Japan (2021),Action|Horror
86534,288975,The Men Who Made the Movies: Howard Hawks (1973),Documentary
86535,288977,Skinford: Death Sentence (2023),Crime|Thriller
86536,288983,UNZIPPED: An Autopsy of American Inequality (2...,Documentary

### Ratings

   userId  movieId  rating   timestamp
0       1        1     4.0  1225734739
1       1      110     4.0  1225865086
2       1      158     4.0  1225733503
3       1      260     4.5  1225735204
4       1      356     5.0  1225735119

          userId  movieId  rating   timestamp
33832157  330975     8340     2.0  1091583256
33832158  330975     8493     2.5  1091585709
33832159  330975     8622     4.0  1091581777
33832160  330975     8665     3.0  1091581765
33832161  330975     8783     2.5  1091581799

### Links

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

       movieId    imdbId     tmdbId
86532   288967  14418234   845861.0
86533   288971  11162178   878958.0
86534   288975     70199   150392.0
86535   288977  23050520  1102551.0
86536   288983  11644948   940588.0

### Tags

   userId  movieId            tag   timestamp
0      10      260   good vs evil  1430666558
1      10      260  Harrison Ford  1430666505
2      10      260         sci-fi  1430666538
3      14     1221      Al Pacino  1311600756
4      14     1221          mafia  1311600746

         userId  movieId                  tag   timestamp
2328310  330923   176599  politically correct  1507547491
2328311  330933     3317        coming of age  1351279384
2328312  330933     3317            sexuality  1351279389
2328313  330947     5782       Not Luc Besson  1154110902
2328314  330947    44191           comic book  1154271525

In [8]:
len(df_tags[df_tags["tag"].isna()])

17

In [9]:
len(df_tags)

2328315

In [10]:
df_tags_not_null = df_tags.dropna(subset=["tag"]).copy()

In [11]:
len(df_tags_not_null) - len(df_tags)

-17

In [12]:
df_tags_not_null[df_tags_not_null["movieId"].isna()]

Empty DataFrame
Columns: [userId, movieId, tag, timestamp]
Index: []

In [13]:
df_tags_not_null[df_tags_not_null["userId"].isna()]

Empty DataFrame
Columns: [userId, movieId, tag, timestamp]
Index: []

In [14]:
df_movies[df_movies["movieId"].isna()]

Empty DataFrame
Columns: [movieId, title, genres]
Index: []

In [15]:
df_movies_new = df_movies
df_movies_new["genres"] = df_movies_new["genres"].str.replace("|", " ", regex=False)

In [16]:
df_movies_new

,movieId,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
86532,288967,State of Siege: Temple Attack (2021),Action Drama
86533,288971,Ouija Japan (2021),Action Horror
86534,288975,The Men Who Made the Movies: Howard Hawks (1973),Documentary
86535,288977,Skinford: Death Sentence (2023),Crime Thriller
86536,288983,UNZIPPED: An Autopsy of American Inequality (2...,Documentary

In [17]:
df_tags_not_null = (df_tags_not_null.groupby("movieId")["tag"]
                                             .apply(lambda x: " ".join(x.astype(str)))
                                             .reset_index()
                                             )

In [18]:
df_tags_not_null

       movieId                                                tag
0            1  animation friendship toys animation Disney Pix...
1            2  animals based on a book fantasy magic board ga...
2            3  sequel moldy old old age old men wedding old p...
3            4  characters chick flick girl movie characters c...
4            5  family pregnancy wedding 4th wall aging baby d...
...        ...                                                ...
53447   288765  post-apocalyptic survival tw suicide apocalyps...
53448   288779                                 Don Camillo Series
53449   288849                     addiction animation short film
53450   288937                                              anime
53451   288955  catalan Costa brava flatmate Millennials slow ...

[53452 rows x 2 columns]

In [19]:
df_movies_new = df_movies_new.merge(df_tags_not_null,
                                    on="movieId",
                                    how="left")

In [20]:
df_movies_new

,movieId,title,genres,tag
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,animation friendship toys animation Disney Pix...
1,2,Jumanji (1995),Adventure Children Fantasy,animals based on a book fantasy magic board ga...
2,3,Grumpier Old Men (1995),Comedy Romance,sequel moldy old old age old men wedding old p...
3,4,Waiting to Exhale (1995),Comedy Drama Romance,characters chick flick girl movie characters c...
4,5,Father of the Bride Part II (1995),Comedy,family pregnancy wedding 4th wall aging baby d...
...,...,...,...,...
86532,288967,State of Siege: Temple Attack (2021),Action Drama,NaN
86533,288971,Ouija Japan (2021),Action Horror,NaN
86534,288975,The Men Who Made the Movies: Howard Hawks (1973),Documentary,NaN
86535,288977,Skinford: Death Sentence (2023),Crime Thriller,NaN
86536,288983,UNZIPPED: An Autopsy of American Inequality (2...,Documentary,NaN

In [21]:
df_movies_new[df_movies_new["tag"].isna()]

,movieId,title,genres,tag
50,51,Guardian Angel (1994),Action Drama Thriller,NaN
55,56,Kids of the Round Table (1995),Adventure Children Comedy Fantasy,NaN
83,84,Last Summer in the Hamptons (1995),Comedy Drama,NaN
89,90,The Journey of August King (1995),Drama,NaN
106,108,Catwalk (1996),Documentary,NaN
...,...,...,...,...
86532,288967,State of Siege: Temple Attack (2021),Action Drama,NaN
86533,288971,Ouija Japan (2021),Action Horror,NaN
86534,288975,The Men Who Made the Movies: Howard Hawks (1973),Documentary,NaN
86535,288977,Skinford: Death Sentence (2023),Crime Thriller,NaN
86536,288983,UNZIPPED: An Autopsy of American Inequality (2...,Documentary,NaN

In [22]:
df_movies_new["tag"] = df_movies_new["tag"].fillna("")

In [23]:
df_movies_new

,movieId,title,genres,tag
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,animation friendship toys animation Disney Pix...
1,2,Jumanji (1995),Adventure Children Fantasy,animals based on a book fantasy magic board ga...
2,3,Grumpier Old Men (1995),Comedy Romance,sequel moldy old old age old men wedding old p...
3,4,Waiting to Exhale (1995),Comedy Drama Romance,characters chick flick girl movie characters c...
4,5,Father of the Bride Part II (1995),Comedy,family pregnancy wedding 4th wall aging baby d...
...,...,...,...,...
86532,288967,State of Siege: Temple Attack (2021),Action Drama,
86533,288971,Ouija Japan (2021),Action Horror,
86534,288975,The Men Who Made the Movies: Howard Hawks (1973),Documentary,
86535,288977,Skinford: Death Sentence (2023),Crime Thriller,
86536,288983,UNZIPPED: An Autopsy of American Inequality (2...,Documentary,

In [24]:
df_movies_new["features"] = df_movies_new["genres"] + " " + df_movies_new["tag"]

In [25]:
df_movies_new

,movieId,title,genres,tag,features
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,animation friendship toys animation Disney Pix...,Adventure Animation Children Comedy Fantasy an...
1,2,Jumanji (1995),Adventure Children Fantasy,animals based on a book fantasy magic board ga...,Adventure Children Fantasy animals based on a ...
2,3,Grumpier Old Men (1995),Comedy Romance,sequel moldy old old age old men wedding old p...,Comedy Romance sequel moldy old old age old me...
3,4,Waiting to Exhale (1995),Comedy Drama Romance,characters chick flick girl movie characters c...,Comedy Drama Romance characters chick flick gi...
4,5,Father of the Bride Part II (1995),Comedy,family pregnancy wedding 4th wall aging baby d...,Comedy family pregnancy wedding 4th wall aging...
...,...,...,...,...,...
86532,288967,State of Siege: Temple Attack (2021),Action Drama,,Action Drama
86533,288971,Ouija Japan (2021),Action Horror,,Action Horror
86534,288975,The Men Who Made the Movies: Howard Hawks (1973),Documentary,,Documentary
86535,288977,Skinford: Death Sentence (2023),Crime Thriller,,Crime Thriller
86536,288983,UNZIPPED: An Autopsy of American Inequality (2...,Documentary,,Documentary

In [26]:
df_movies_new[["title","features"]].sample(10)

,title,features
81675,Watcher (2022),Horror Mystery Thriller atmospheric horror buc...
10100,Bad News Bears (2005),Children Comedy Billy Bob Thornton comedy curs...
30845,The Brooke Ellison Story (2004),Drama college inspirational true story Christo...
44887,The Salt Prince (1983),Children Fantasy fairy tale
67250,EvenHand (2002),Drama
68076,Do Not Be Deceived (2018),Mystery Thriller
38189,Last Stop (2002),Documentary
83248,Nuvve Kavali (2000),Children Drama Romance
15005,Restless (Uro) (2006),Action Crime Thriller
62937,For Sama (2019),Documentary believe in yourself Disturbing do...

In [27]:
df_movies_new[df_movies_new["genres"] == "(no genres listed)"].shape[0]

7060

In [28]:
df_movies_new[df_movies_new["features"] == "(no genres listed) "].shape[0]

4270

In [29]:
df_movies_new_new = df_movies_new[df_movies_new["features"] != "(no genres listed) "].copy()

In [30]:
df_movies_new_new["genres"] = df_movies_new_new["genres"].replace(
    "(no genres listed)",
    ""
)

df_movies_new_new["features"] = (df_movies_new_new["genres"] + " " + df_movies_new_new["tag"]).str.strip()

In [31]:
(df_movies_new_new["features"] == "").sum()

np.int64(0)

In [32]:
len(df_movies_new_new)

82267

In [33]:
len(df_movies)

86537

In [34]:
len(df_movies) - len(df_movies_new_new)

4270

In [48]:
df_movies_new_new[["title","features"]].sample(10)

,title,features
38070,Elevator Movie (2004),Comedy Drama trapped in an elevator
18791,All About Actresses (Le bal des actrices) (2009),Comedy Drama woman director
15493,Woman in the Moon (By Rocket to the Moon) (Fra...,Comedy Drama Romance Sci-Fi inventor moon sci-...
69628,Fatima (2020),Children Drama Netflix Streaming Catholicism m...
48615,Jungle (2017),Action Adventure Drama Daniel Radcliffe forest...
44373,The Matchbreaker (2016),Comedy Romance
23206,Farm House (2008),Horror Mystery Thriller
76345,12 Mighty Orphans (2021),Drama great depression sports true story under...
79442,Spoiled Brats (2021),Comedy cars comedy con family French house Mar...
81488,La matanza caníbal de los garrulos lisérgicos ...,Comedy Horror

In [81]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [82]:
df_movies_new_new = df_movies_new_new.reset_index(drop=True)
tfidf = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf.fit_transform(df_movies_new_new["features"])

In [83]:
tfidf_matrix.shape

(82267, 51796)

In [84]:
indices = pd.Series(
    df_movies_new_new.index,
    index = df_movies_new_new["title"]
).drop_duplicates()

In [85]:
indices["Elevator Movie (2004)"]

np.int64(37058)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(movie_title, n=5):
    idx = indices[movie_title]

    similarities = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    similar_indices = similarities.argsort()[::-1]
    similar_indices = similar_indices[1:n+1]

    return df_movies_new_new.iloc[similar_indices][["title", "genres"]]

In [87]:
recommend("Toy Story (1995)")

                       title                                            genres
3021      Toy Story 2 (1999)       Adventure Animation Children Comedy Fantasy
2264    Bug's Life, A (1998)               Adventure Animation Children Comedy
14815     Toy Story 3 (2010)  Adventure Animation Children Comedy Fantasy IMAX
38681    Finding Dory (2016)                        Adventure Animation Comedy
4781   Monsters, Inc. (2001)       Adventure Animation Children Comedy Fantasy

In [88]:
recommend("Jumanji (1995)")

                             title                   genres
1638                Flubber (1997)  Children Comedy Fantasy
8226         Final Cut, The (2004)          Sci-Fi Thriller
495          Mrs. Doubtfire (1993)             Comedy Drama
13795  World's Greatest Dad (2009)             Comedy Drama
749                    Jack (1996)             Comedy Drama

In [91]:
recommend("Elämältä kaiken sain")

                         title        genres
53823    Berlin Calling (2008)  Comedy Drama
53677  Teefa In Trouble (2018)  Comedy Drama
53688      Normal Doors (2015)  Comedy Drama
53691  Trieste Is Ours! (2009)  Comedy Drama
53705    Magalir Mattum (1994)  Comedy Drama

In [92]:
recommend("Murattu Kalai (1980)")

                     title                 genres
52168         Aegan (2008)         Action Romance
52182  Bengal Tiger (2015)  Action Comedy Romance
52195     Bagavathi (2002)         Action Romance
52176       Thimiru (2006)         Action Romance
52187         Theri (2016)         Action Romance

In [93]:
recommend("Animal Kingdom, The (1932)")

                           title       genres
25776          Lost Angel (1943)        Drama
38545  In Jackson Heights (2015)  Documentary
18661         Letter, The (2012)        Drama
5588         Times Square (1980)        Drama
33055       From the Head (2011)        Drama

In [90]:
df_movies_new_new.sample(50)

,movieId,title,genres,tag,features
52150,187827,Murattu Kalai (1980),Action Romance,action comedy,Action Romance action comedy
52482,188537,Intensity (1997),Drama Horror Thriller,child kidnapping murder serial killer,Drama Horror Thriller child kidnapping murder ...
27820,130420,Outrage (1973),Crime Drama Thriller,based on a true story california gang killing ...,Crime Drama Thriller based on a true story cal...
40522,161660,Gut zu Vögeln (2016),Comedy Romance,,Comedy Romance
80357,282303,Gay Sex in the 70s (2005),Documentary,,Documentary
51341,186025,Killer nurse (2008),Crime Horror,,Crime Horror
12891,64784,"Animal Kingdom, The (1932)",Drama Romance,BD-R butler new york city,Drama Romance BD-R butler new york city
39755,159904,Living on Love (1937),Comedy Romance,apartment heiress struggling artist truck driv...,Comedy Romance apartment heiress struggling ar...
11884,55417,Irina Palm (2007),Drama,seen 2011 ambulance female friendship hospital...,Drama seen 2011 ambulance female friendship ho...
60911,208539,Cousins (2019),Comedy Romance,ex-con homosexuality incest,Comedy Romance ex-con homosexuality incest
15424,81305,Eyes Wide Open (Einayim Petukhoth) (2009),Drama,forbidden love haredi hebrew israeli subtle 01...,Drama forbidden love haredi hebrew israeli sub...
31573,139533,The Secret Village (2013),Mystery Thriller,atrocious acting atrocious dialogue atrocious ...,Mystery Thriller atrocious acting atrocious di...
73840,258637,The Voyeurs (2021),Thriller,genre:Psychological Thriller Nudity (Topless -...,Thriller genre:Psychological Thriller Nudity (...
79456,279980,Skyman (2020),Horror Sci-Fi,aliens unrealistic plot,Horror Sci-Fi aliens unrealistic plot
54082,192379,First Man (2018),Drama,Justin Hurwitz space race Apollo 11 astronaut ...,Drama Justin Hurwitz space race Apollo 11 astr...
14599,77332,Don's Plum (2001),Drama,,Drama
536,541,Blade Runner (1982),Action Sci-Fi Thriller,classic dystopia sci-fi aesthetic science fict...,Action Sci-Fi Thriller classic dystopia sci-fi...
30002,135631,Three Wise Guys (2005),Comedy,,Comedy
9893,33145,"Lot Like Love, A (2005)",Comedy Drama Romance,happy ending love romance Ashton Kutcher happy...,Comedy Drama Romance happy ending love romance...
56230,197253,Diana and I (2017),Drama,,Drama
57823,200950,Game of Thrones - Conquest & Rebellion (2017),Animation Fantasy,,Animation Fantasy
53614,191237,All I Need (2016),Horror Thriller,,Horror Thriller
22094,113394,"Pretty One, The (2013)",Comedy Drama,amnesia romcom twins Zoe Kazan double life fak...,Comedy Drama amnesia romcom twins Zoe Kazan do...
79155,279156,Strange Codes (1972),Documentary,,Documentary
40919,162550,Riding The Bus With My Sister (2005),,woman director,woman director
24431,121401,Love Child (1982),Crime Drama Romance,,Crime Drama Romance
55922,196531,After Everything (2018),Comedy Drama Romance,might like,Comedy Drama Romance might like
75437,265604,Felix Gets Broadcasted (1923),Animation,,Animation
1970,2059,"Parent Trap, The (1998)",Children Comedy Romance,camping trip family family friendly irrealisti...,Children Comedy Romance camping trip family fa...
52543,188677,Wu: The Story of the Wu-Tang Clan (2008),Documentary,,Documentary
49126,181099,A Tree of Palme (2002),Adventure Animation Drama Fantasy Romance,,Adventure Animation Drama Fantasy Romance
78681,277818,Be Prepared (2018),Thriller,camp Poland scout scouting scouts,Thriller camp Poland scout scouting scouts
80212,281920,When It Melts,Drama,,Drama
57170,199442,Thimiru Pudichavan (2018),Action Drama,,Action Drama
62791,213401,Beyond the Wall of Sleep (2006),Horror,,Horror
78419,277042,Honor Society (2022),Comedy,over 45 paramount reviewed high school teen mo...,Comedy over 45 paramount reviewed high school ...
13130,66904,Playing for Keeps (1986),Comedy,anger arrest aspiration bandage over eye bank ...,Comedy anger arrest aspiration bandage over ey...
47765,177905,The Mouth Agape (1974),Drama,death infidelity death mother son relationship...,Drama death infidelity death mother son relati...
10720,44657,Mouchette (1967),Drama,bleak DEATH OF A PARENT deliberate downbeat KI...,Drama bleak DEATH OF A PARENT deliberate downb...
6572,6694,Suddenly (Tan de Repente) (2002),Comedy Drama,,Comedy Drama
30866,137741,The Nostradamus Kid (1993),,Australia Australian,Australia Australian
51276,185883,Laugh or Die (2018),Comedy Drama,dark comedy finnish civil war island prison,Comedy Drama dark comedy finnish civil war isl...
2995,3088,Harvey (1950),Comedy Fantasy,James Stewart classical James Stewart Jimmy St...,Comedy Fantasy James Stewart classical James S...
68979,234500,A Christmas Hero (2020),Children Drama Fantasy,,Children Drama Fantasy
51200,185713,The Cambridge Squatter (2017),Documentary Drama,woman director,Documentary Drama woman director
5133,5240,Running Scared (1980),Action Drama,boat chase cold war escape florida independent...,Action Drama boat chase cold war escape florid...
68633,232945,Sweet Autumn (2020),Romance,,Romance
72892,253608,Hand Rolled Cigarette (2021),Crime Drama,,Crime Drama
48762,180227,God: Serengeti (2017),Comedy,Fantasy Neil Blomkamp Oats Studios short,Comedy Fantasy Neil Blomkamp Oats Studios short
34396,146344,Elämältä kaiken sain,Comedy Drama,,Comedy Drama